import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <Head>
        <meta name="robots" content="noindex" />
        <title>Shift Panel Example</title>
      </Head>
      <body className={`${inter.className} bg-background light`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
